export const COUNTRIES = [
    { Id: 1, Name: 'USA' },
    { Id: 2, Name: 'Canada' }
]

export const STATES = [
    { Id: 1, Code: "AL", Name: "Alabama", CountryId: 1 },
    { Id: 2, Code: "AK", Name: "Alaska", CountryId: 1 },
    { Id: 3, Code: "AZ", Name: "Arizona", CountryId: 1 },
    { Id: 4, Code: "AR", Name: "Arkansas", CountryId: 1 },
    { Id: 5, Code: "CA", Name: "California", CountryId: 1 },
    { Id: 6, Code: "CO", Name: "Colorado", CountryId: 1 },
    { Id: 7, Code: "CT", Name: "Connecticut", CountryId: 1 },
    { Id: 8, Code: "DE", Name: "Delaware", CountryId: 1 },
    { Id: 9, Code: "DC", Name: "District Of Columbia", CountryId: 1 },
    { Id: 10, Code: "FL", Name: "Florida", CountryId: 1 },
    { Id: 11, Code: "GA", Name: "Georgia", CountryId: 1 },
    { Id: 12, Code: "HI", Name: "Hawaii", CountryId: 1 },
    { Id: 13, Code: "ID", Name: "Idaho", CountryId: 1 },
    { Id: 14, Code: "IL", Name: "Illinois", CountryId: 1 },
    { Id: 15, Code: "IN", Name: "Indiana", CountryId: 1 },
    { Id: 16, Code: "IA", Name: "Iowa", CountryId: 1 },
    { Id: 17, Code: "KS", Name: "Kansas", CountryId: 1 },
    { Id: 18, Code: "KY", Name: "Kentucky", CountryId: 1 },
    { Id: 19, Code: "LA", Name: "Louisiana", CountryId: 1 },
    { Id: 20, Code: "ME", Name: "Maine", CountryId: 1 },
    { Id: 21, Code: "MD", Name: "Maryland", CountryId: 1 },
    { Id: 22, Code: "MA", Name: "Massachusetts", CountryId: 1 },
    { Id: 23, Code: "MI", Name: "Michigan", CountryId: 1 },
    { Id: 24, Code: "MN", Name: "Minnesota", CountryId: 1 },
    { Id: 25, Code: "MS", Name: "Mississippi", CountryId: 1 },
    { Id: 26, Code: "MO", Name: "Missouri", CountryId: 1 },
    { Id: 27, Code: "MT", Name: "Montana", CountryId: 1 },
    { Id: 28, Code: "NE", Name: "Nebraska", CountryId: 1 },
    { Id: 29, Code: "NV", Name: "Nevada", CountryId: 1 },
    { Id: 30, Code: "NH", Name: "New Hampshire", CountryId: 1 },
    { Id: 31, Code: "NJ", Name: "New Jersey", CountryId: 1 },
    { Id: 32, Code: "NM", Name: "New Mexico", CountryId: 1 },
    { Id: 33, Code: "NY", Name: "New York", CountryId: 1 },
    { Id: 34, Code: "NC", Name: "North Carolina", CountryId: 1 },
    { Id: 35, Code: "ND", Name: "North Dakota", CountryId: 1 },
    { Id: 36, Code: "OH", Name: "Ohio", CountryId: 1 },
    { Id: 37, Code: "OK", Name: "Oklahoma", CountryId: 1 },
    { Id: 38, Code: "OR", Name: "Oregon", CountryId: 1 },
    { Id: 39, Code: "PA", Name: "Pennsylvania", CountryId: 1 },
    { Id: 40, Code: "RI", Name: "Rhode Island", CountryId: 1 },
    { Id: 41, Code: "SC", Name: "South Carolina", CountryId: 1 },
    { Id: 42, Code: "SD", Name: "South Dakota", CountryId: 1 },
    { Id: 43, Code: "TN", Name: "Tennessee", CountryId: 1 },
    { Id: 44, Code: "TX", Name: "Texas", CountryId: 1 },
    { Id: 45, Code: "UT", Name: "Utah", CountryId: 1 },
    { Id: 46, Code: "VT", Name: "Vermont", CountryId: 1 },
    { Id: 47, Code: "VA", Name: "Virginia", CountryId: 1 },
    { Id: 48, Code: "WA", Name: "Washington", CountryId: 1 },
    { Id: 49, Code: "WV", Name: "West Virginia", CountryId: 1 },
    { Id: 50, Code: "WI", Name: "Wisconsin", CountryId: 1 },
    { Id: 51, Code: "WY", Name: "Wyoming", CountryId: 1 },

    { Id: 52, Code: "AB", Name: "Alberta", CountryId: 2 },
    { Id: 53, Code: "BC", Name: "British Columbia", CountryId: 2 },
    { Id: 54, Code: "MB", Name: "Manitoba", CountryId: 2 },
    { Id: 55, Code: "NB", Name: "New Brunswick", CountryId: 2 },
    { Id: 56, Code: "NL", Name: "Newfoundland and Labrador", CountryId: 2 },
    { Id: 57, Code: "NS", Name: "Nova Scotia", CountryId: 2 },
    { Id: 58, Code: "ON", Name: "Ontario", CountryId: 2 },
    { Id: 59, Code: "PE", Name: "Prince Edward Island", CountryId: 2 },
    { Id: 60, Code: "QC", Name: "Quebec", CountryId: 2 },
    { Id: 61, Code: "SK", Name: "Saskatchewan", CountryId: 2 },
    { Id: 62, Code: "NT", Name: "Northwest Territories", CountryId: 2 },
    { Id: 63, Code: "NU", Name: "Nunavut", CountryId: 2 },
    { Id: 64, Code: "YT", Name: "Yukon", CountryId: 2 },
]

export const MESSAGES = {
    TokeExpireMessage : 'The token is expired'
}
export const DEFAULTIMAGES ={
    UserImage : '../../assets/images/nophoto.png',
    FarmImage:'../../assets/images/nologo.jpg'
}